[package]
name = "todo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
clap = "4.0"
features = "0.10.0"
derive = "1.0.0"
